# Generated by Django 3.2.8 on 2021-10-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('I', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], default='L', max_length=1, verbose_name='Dia de la semana')),
                ('hora', models.DateTimeField(verbose_name='Hora')),
            ],
            options={
                'ordering': ['dia', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, verbose_name='Nro de Telefono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('web', models.CharField(blank=True, max_length=100, null=True, verbose_name='Web')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimiento_localidad', to='odontologia.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichaAlta', models.DateField(auto_now_add=True, verbose_name='Ficha Alta')),
                ('tipoFactorSangre', models.CharField(max_length=10, verbose_name='Tipo y Factor de Sangre')),
                ('antecedentes', models.TextField(blank=True, null=True, verbose_name='Antecedentes')),
                ('medicacion', models.CharField(max_length=100, verbose_name='Medicacion')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichaMedica_establecimiento', to='odontologia.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('nombreOS', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre Obra Social')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('disponible', models.BooleanField(verbose_name='Disponible')),
            ],
            options={
                'verbose_name_plural': 'ObrasSociales',
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Pieza Dental')),
            ],
            options={
                'verbose_name_plural': 'PiezasDentales',
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Prestacion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('piezaDental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_piezaDental', to='odontologia.piezadental')),
            ],
            options={
                'verbose_name_plural': 'Prestaciones',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matricula')),
                ('especialidad', models.CharField(max_length=120, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_fecha', to='odontologia.calendario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_medico', to='odontologia.profesional')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_prestacion', to='odontologia.prestacion')),
            ],
            options={
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_doc',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='Nro Documento'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('contrasenia', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_persona', to='odontologia.persona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_fecha', to='odontologia.calendario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_medico', to='odontologia.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_persona', to='odontologia.persona')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento_Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_prestacion_prestacion', to='odontologia.prestacion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_prestacion_tratamiento', to='odontologia.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesional_persona', to='odontologia.persona'),
        ),
        migrations.CreateModel(
            name='Prestacion_PiezaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piezaDental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_piezaDental_piezaDental', to='odontologia.piezadental')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_piezaDental_prestacion', to='odontologia.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('numeroHC', models.IntegerField(primary_key=True, serialize=False)),
                ('numOS', models.IntegerField()),
                ('titularFamiliar', models.CharField(max_length=100, verbose_name='Titular Obra Social')),
                ('obraSocial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_obraSocial', to='odontologia.obrasocial')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_persona', to='odontologia.persona')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='FMedica_Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichaMedica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fMedica_tratamiento_fichaMedica', to='odontologia.fichamedica')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fMedica_tratamiento_tratamiento', to='odontologia.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='historiaClinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichaMedica_paciente', to='odontologia.persona'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichaMedica_prestacion', to='odontologia.prestacion'),
        ),
        migrations.CreateModel(
            name='Calendario_Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendario_turno_calendario', to='odontologia.calendario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendario_turno_turno', to='odontologia.turno')),
            ],
        ),
    ]
